---
- include_tasks: remove_nginx.yml

- name: Install HAproxy
  apt:
     name: haproxy
     state: present

- name: Install HAproxy systemd config
  copy:
    src: "{{ haproxy_service_file }}"
    dest: /etc/systemd/system/haproxy.service
  notify: reload systemd

- name: Replace HAproxy wrapper in debian 10
  replace:
     path: "/etc/systemd/system/haproxy.service"
     regexp: "/usr/sbin/haproxy-systemd-wrapper"
     replace: "/usr/sbin/haproxy -Ws"
  when: ansible_distribution_release == "buster"

- name: Start and enable HAProxy service
  service: name=haproxy state=started enabled=true

- name: Remove default HAproxy configs
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/haproxy/haproxy.cfg
    - /etc/haproxy/haproxy.cfg.bak
  notify: reload haproxy

- name: Write HAProxy globals and frontend configuration files (Single server)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0664
    owner: haproxy
    group: haproxy
  with_items:
    - { src: '{{ globals_haproxy_template }}', dest: '/etc/haproxy/01-globals.cfg' }
    - { src: '{{ frontend_haproxy_template }}', dest: '/etc/haproxy/03-frontend.cfg' }
  notify: restart haproxy
  when: "'frontend_servers' not in groups and groups['all'] | length() == 1"

- name: Write HAProxy globals configuration file (cluster servers)
  template:
    src: "{{ globals_haproxy_template }}"
    dest: "/etc/haproxy/01-globals.cfg"
    mode: 0664
    owner: haproxy
    group: haproxy
  notify: restart haproxy
  when: "'frontend_servers' in groups and groups['all'] | length() > 1"

- name: Generate the SSL certificate
  template:
    src: haproxy_oldstyle_certificate.j2
    dest: /etc/ssl/certs/server_and_intermediate_and_root.crt
    mode: 0640
  when: ssl_certfile is defined
  notify: reload haproxy

- name: Create the SSL certificate chain
  template:
    src:  server_and_intermediate_and_root.crt.j2
    dest: /etc/ssl/certs/server_and_intermediate_and_root.crt
    mode: 0640
  when: ssl_server_certificate is defined and ssl_intermediate_certificate is defined and ssl_root_certificate is defined
  notify: reload haproxy

- name: Create the SSL intermediate and root certificate file
  template:
    src:  intermediate_and_root.crt.j2
    dest: /etc/ssl/certs/intermediate_and_root.crt
    mode: 0640
  when: ssl_intermediate_certificate is defined and ssl_root_certificate is defined
  notify: reload haproxy

- name: Copy the SSL key
  copy:
    src: "{{ ssl_keyfile }}"
    dest: /etc/ssl/private/teamwire-backend.key
    mode: 0640
  when: ssl_keyfile is defined
  notify: reload haproxy

- name: Copy teamwire intermediate
  copy:
    src: "{{ ssl_intermediate_certificate }}"
    dest: "/etc/ssl/certs/teamwire.intermediate.crt"
    mode: 0640
  when: ssl_intermediate_certificate is defined

- name: Copy teamwire certificate
  copy:
    src: "{{ ssl_server_certificate }}"
    dest: "/etc/ssl/certs/teamwire.server.crt"
    mode: 0640
  when: ssl_server_certificate is defined

- name: Ensure socat is installed
  apt:
    name: socat
    state: present

- name: Copy ocsp.sh to src dir
  copy:
     src: ocsp.sh
     dest: "/usr/local/src/"
     mode: 0750
     owner: root
     group: root
  when: ssl_server_certificate is defined and ssl_intermediate_certificate is defined and ssl_root_certificate is defined

- name: stat ocsp file and register it
  stat:
    path: "{{ ocspfile_path }}"
  register: stat_ocspfile

- name: Add OCSP daily cron job
  cron:
     name: "daily ocsp job to create ocsp file"
     special_time: daily
     job: "/usr/local/src/ocsp.sh > /dev/null"
  ignore_errors: True
  when:
    - ssl_server_certificate is defined and ssl_intermediate_certificate is defined and ssl_root_certificate is defined

- name: Generate a new Diffie-Hellman group
  command: /usr/bin/openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
  when: ssl_keyfile is defined
  args:
    creates: /etc/ssl/private/dhparams.pem

- name: Import SSL certificate check
  import_tasks: ssl-check.yml

# open firewall ports for the web server
- ufw: rule=allow port=80 proto=tcp
  when: config_done is defined

- ufw: rule=allow port=443 proto=tcp
  when: ssl_keyfile is defined

- name: Re-use sockets in TIME_WAIT state for new connections
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: "1"
    state: present

- name: Ensure netfilter can handle a sufficient amount of connections
  sysctl:
    name: net.nf_conntrack_max
    value: "65536"
    state: present

- name: Increase number of socket connection backlog
  sysctl:
    name: net.core.somaxconn
    value: "1024"
    state: present
    reload: yes

- include_tasks: cluster.yml
  when: "'frontend_servers' in groups"
