---
- name: Main Teamwire backend configuration
  copy:
    src: teamwire_backend.conf
    dest: /etc/nginx/conf.d/teamwire_backend.conf
  notify: reload nginx

- name: Teamwire backend configuration (HTTP)
  template:
    src: teamwire-backend-http.j2
    dest: /etc/nginx/sites-available/teamwire-backend-http
  notify: reload nginx

- name: Teamwire backend configuration (HTTPS)
  template:
    src: teamwire-backend-https.j2
    dest: /etc/nginx/sites-available/teamwire-backend-https
  notify: reload nginx

- name: Enable HTTP
  when: ssl_certfile is not defined and ssl_keyfile is not defined
  file:
    src: /etc/nginx/sites-available/teamwire-backend-http
    dest: /etc/nginx/sites-enabled/teamwire-backend-http
    state: link
  notify: reload nginx

- name: Disable HTTP
  when: ssl_certfile is defined and ssl_keyfile is defined
  file:
    path: /etc/nginx/sites-enabled/teamwire-backend-http
    state: absent
  notify: reload nginx

- name: Enable HTTPS
  when: ssl_certfile is defined and ssl_keyfile is defined
  file:
    src: /etc/nginx/sites-available/teamwire-backend-https
    dest: /etc/nginx/sites-enabled/teamwire-backend-https
    state: link
  notify: reload nginx

- name: Disable HTTPS when no certificate is configured
  when: ssl_certfile is not defined and ssl_keyfile is not defined
  file: path="{{ item }}" state=absent
  with_items:
  - /etc/nginx/sites-enabled/teamwire-backend-https
  - /etc/ssl/private/teamwire-backend.key
  - /etc/ssl/private/teamwire-backend.crt
  notify: reload nginx
