---
- name: Install Redis Sentinel
  apt: name=redis-sentinel state=present

- name: Copy systemd unit files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0644
  with_items:
    - redis-server@.service
    - redis-sentinel@.service
  notify: reload systemd

- meta: flush_handlers

- name: Stop and disable the default Redis services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - redis-server
    - redis-sentinel
  register: disabled_redis_default_services

- name: Delete files created by the default Redis services
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /var/log/redis/redis-server.log
    - /var/log/redis/redis-sentinel.log
    - /var/lib/redis/dump.rdb
  when: disabled_redis_default_services.changed

- name: Create Redis instance configuration files
  template:
    src: "{{ item[0] }}.conf.j2"
    dest: "/etc/redis/{{ item[0] }}-{{ item[1] }}.conf"
    owner: redis
    group: redis
    mode: 0640
    force: no
  with_nested:
    - [ 'redis', 'sentinel' ]
    - "{{ redis_instances.keys() }}"
  register: redis_configuration

- name: Create Redis runtime directory
  file:
    name: /var/run/redis
    state: directory
    owner: redis
    group: redis

- name: Start and enable Redis services
  service:
    name: "redis-{{ item[0] }}@{{ item[1] }}"
    state: started
    enabled: yes
  with_nested:
    - [ 'server', 'sentinel']
    - "{{ redis_instances.keys() }}"

- name: Write Redis check scripts for each instance
  template:
    src: redis-check.j2
    dest: "/etc/consul.d/scripts/check-redis-{{ item }}.sh"
    mode: 0755
  with_items:
    - "{{ redis_instances.keys() }}"

- name: Register Redis servers with Consul
  template:
    src: consul-redis.hcl.j2
    dest: "/etc/consul.d/redis-{{ item }}.hcl"
  notify: restart consul
  with_items:
    - "{{ redis_instances.keys() }}"

- name: Register Redis sentinels with Consul
  template:
    src: consul-redis-sentinel.hcl.j2
    dest: "/etc/consul.d/redis-sentinel-{{ item }}.hcl"
  notify: restart consul
  with_items:
    - "{{ redis_instances.keys() }}"

- name: Connect other Redis servers to first Redis server
  redis:
    command: slave
    master_host: "{{ groups['redis_servers'] | first }}"
    master_port: "{{ redis_instances[item].server_port }}"
    login_port: "{{ redis_instances[item].server_port }}"
    login_password: "{{ redis_instances[item].password if redis_instances[item].password else omit }}"
  when: inventory_hostname != groups['redis_servers'] | first and redis_configuration.changed
  with_items:
    - "{{ redis_instances.keys() }}"
