- name: Install Redis
  apt: name={{item}} state=present
  with_items:
  - redis-server
  - redis-tools
  - python-redis

- name: Configure redis to listen on the docker0 interface
  action: lineinfile dest=/etc/redis/redis.conf regexp="^bind\s+127.0.0.1" line="bind 127.0.0.1 172.17.42.1"
  notify: restart redis

- name: Start and enable Redis server
  service: name=redis-server state=started enabled=yes
