---
- name: Install Redis
  apt: name={{item}} state=present
  with_items:
  - redis-tools
  - python-redis

# See http://redis.io/topics/faq for details
- name: Enable vm.overcommit_memory for Redis
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes

- name: Increase number of socket connection backlog
  sysctl:
    name: net.core.somaxconn
    value: 1024
    state: present
    reload: yes

- include: single.yml
  when: "'redis_servers' not in groups"

- include: cluster.yml
  when: "'redis_servers' in groups"
