---
- name: Install Redis server
  apt: name=redis-server state=present

- name: Configure Redis to listen on all interfaces
  action: lineinfile dest=/etc/redis/redis.conf regexp="^bind\s+127.0.0.1" backrefs=yes line="bind 0.0.0.0"
  notify: restart redis

- name: Configure password for Redis
  action: lineinfile dest=/etc/redis/redis.conf regexp="^(# )+requirepass" backrefs=yes line="requirepass {{ redis_pass }}"
  when: redis_pass is defined
  notify: restart redis

- name: Start and enable Redis server
  service: name=redis-server state=started enabled=yes
