---
- name: Install Galera and requirements
  apt: name={{ item }} state=present
  with_items:
  - galera
  - mytop
  - rsync
  - socat

- name: Write Galera cluster configuration
  template: src=cluster.conf.j2 dest=/etc/mysql/conf.d/cluster.cnf mode=644

- name: Create clustercheck database user
  mysql_user: host=localhost name=clustercheck password="{{ clustercheck_password }}" priv="*.*:PROCESS" login_user=root login_password="{{mysql_root_password}}"
  when: inventory_hostname == groups['database_servers'][0]

# Clustercheck script from https://github.com/olafz/percona-clustercheck
# Licensed under the BSD license
- name: Install Galera cluster check script
  copy: src=clustercheck dest=/usr/local/bin/clustercheck mode=0755

- name: Ensure pip and python-requests are installed
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
  - python-pip
  - python-requests

- name: Check if a wheelhouse exists
  stat: path=/var/cache/wheelhouse
  register: wheelhouse

- name: Ensure python-consul module is installed (online)
  pip: name=python-consul version=0.6.1
  when: not wheelhouse.stat.exists

- name: Ensure python-consul module is installed (offline)
  pip: name=/var/cache/wheelhouse/python_consul-0.6.1-py2-none-any.whl
  when: wheelhouse.stat.exists

- name: Register MariaDB database and its health check in Consul
  consul:
    service_name: galera
    service_port: 3306
    script: "/usr/local/bin/clustercheck clustercheck {{ clustercheck_password }} 1"
    interval: 30s
