---
- name: Ensure xtrabackup_password is configured before installing the Database
  fail: msg="Database replication user password is not defined. Please check the configuration file"
  when: xtrabackup_password is not defined or xtrabackup_password == None

- name: Check if the Percona repository signing key needs to be installed
  shell: bash -c "gpg --keyring /etc/apt/trusted.gpg -k 9334A25F8507EFA5 > /dev/null 2>&1 && echo present || echo absent"
  register: percona_repo_key
  changed_when: False
  when: ansible_distribution == "Debian"

- name: Add Percona repo signing key (direct)
  apt_key:
    id: 9334A25F8507EFA5
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
  when: percona_repo_key.stdout == "absent" and http_proxy is not defined

- name: Add Percona repo signing key (via proxy)
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --keyserver-options http-proxy="{{http_proxy}}" --recv-keys 9334A25F8507EFA5
  when: percona_repo_key.stdout == "absent" and http_proxy is defined

- name: Configure Percona repository (cluster setups)
  apt_repository: repo="deb http://repo.percona.com/apt {{ ansible_distribution_release }} main" state=present update_cache=yes

- name: Install Galera and requirements (Debian 8)
  apt: name={{ item }} state=present
  with_items:
  - galera
  - mytop
  - percona-xtrabackup-24
  - socat
  when: ansible_distribution == "Debian" and ansible_distribution_release == 'jessie'

# Debian 9 includes mytop in the mariadb package, but has some broken dependencies
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863596
- name: Install Galera and requirements (Debian 9)
  apt: name={{ item }} state=present
  with_items:
  - galera
  - libconfig-inifiles-perl
  - libterm-readkey-perl
  - percona-xtrabackup-24
  - socat
  when: ansible_distribution == "Debian" and ansible_distribution_release == 'stretch'

- name: Create database replication user
  mysql_user:
    host: localhost
    name: xtrabackup
    password: "{{ xtrabackup_password }}"
    priv: "*.*:RELOAD,LOCK TABLES,REPLICATION CLIENT,PROCESS"
    login_user: root
    login_password: "{{mysql_root_password}}"
  when: inventory_hostname == groups['database_servers'][0]

- name: Write Galera cluster configuration
  template:
    src: cluster.conf.j2
    dest: /etc/mysql/conf.d/cluster.cnf
    mode: 0644

- name: Create clustercheck database user
  mysql_user:
    name: clustercheck
    host: localhost
    password: "{{ clustercheck_password }}"
    priv: "*.*:PROCESS"
    login_user: root
    login_password: "{{mysql_root_password}}"
  when: inventory_hostname == groups['database_servers'][0]

# Clustercheck script from https://github.com/olafz/percona-clustercheck
# Licensed under the BSD license
- name: Install Galera cluster check script
  copy: src=clustercheck dest=/usr/local/bin/clustercheck mode=0755

- name: Copy systemd clustercheck socket configuration
  copy:
    src: clustercheck.socket
    dest: /etc/systemd/system/clustercheck.socket
    mode: 0640
  notify:
    - reload systemd

- name: Write systemd clustercheck service
  template:
    src: clustercheck@.service.j2
    dest: /etc/systemd/system/clustercheck@.service
    mode: 0644
  notify:
    - reload systemd

- meta: flush_handlers

- name: Enable the clustercheck service
  service: name=clustercheck.socket state=started enabled=true
