---
- name: Install MySQL
  apt: name={{item}} state=present
  with_items:
  - mariadb-server
  - mariadb-client
  - python-mysqldb

# Unfortunately MySQL cannot be configure to listen on multiple interfaces
- name: Configure MySQL to listen on all interfaces
  action: lineinfile dest=/etc/mysql/my.cnf regexp="^bind-address\s+=\s+127.0.0.1" line="bind-address=0.0.0.0"
  notify: restart MySQL

- name: Start and enable MySQL server
  service: name=mysql state=started enabled=yes

- name: Create Teamwire database
  mysql_db: name=teamwire state=present

- name: Create Teamwire database user
  mysql_user: name=teamwire host=% password={{teamwire_db_password}} priv=teamwire.*:ALL state=present

- name: Install Redis
  apt: name={{item}} state=present
  with_items:
  - redis-server
  - redis-tools
  - python-redis

- name: Configure redis to listen on the docker0 interface
  action: lineinfile dest=/etc/redis/redis.conf regexp="^bind\s+127.0.0.1" line="bind 127.0.0.1 172.17.42.1"
  notify: restart redis

- name: Start and enable Redis server
  service: name=redis-server state=started enabled=yes
