---
- name: Configure replication
  template: src=replication.cnf.j2 dest=/etc/mysql/conf.d/replication.cnf
  notify: restart MariaDB

- name: Open access to MySQL port to partner node
  ufw:
    rule: allow
    port: 3306
    from: "{{ partner_node }}"

- name: Create replication DB user
  mysql_user:
    name: repl
    host: "{{ partner_node }}"
    password: "{{replication_password}}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
