# This playbook applies to backend cluster nodes, not the single server installation
# The Hashi servers need to be run individually.
- name: Configure Consul on Hashi server nodes
  hosts: hashi_servers
  serial: 1
  roles:
  - role: ../../roles/consul

- name: Configure Consul on Consul member nodes
  hosts: all:!hashi_servers
  roles:
  - role: ../../roles/consul
