# This play only applies to the single server installation
- hosts: local
  tasks:
  - include: "../../roles/backend/tasks/single_{{ ansible_distribution }}.yml"

# This play only applies to cluster installations
# It needs to run on the Nomad client agent nodes
- name: Deploy the backend containers
  hosts: consul_servers
  tasks:
  - { include: ../../roles/backend/tasks/cluster.yml, when: "'backend_servers' in groups" }
