- name: Deploy Docker (registry host)
  hosts: docker_registry
  roles:
  - role: ../../roles/docker

- name: Deploy Docker (non-registry hosts)
  hosts: redis_servers:backend_servers:local:!docker_registry
  roles:
  - role: ../../roles/docker
