- hosts: local:management_servers
  roles:
  - role: ../../roles/management

- name: Clean-up non-management servers
  hosts: all:!management_servers
  tasks:
    - include_role:
        name: ../../roles/management
        tasks_from: cleanup
      when: groups['all'] | length() > 1
