- name: Ensure valid management server configuration
  hosts: all
  tasks:
  - assert:
     that:
       - "'management_servers' in groups"
       - groups['management_servers'] | length > 0
     msg:
       - "WARNING: No management servers have been defined."
       - "Management servers (group: management_servers), is a new management server group which you'll run twctl and Ansible provisions from."
       - "WARNING: You must ensure all the relevant certificates, cluster_hosts and group_vars/all files are moved/adapted to the assigned management servers before proceeding."
       - "You should also ensure the Vault token is in place at /root/.vault-token and /home/teamwire/.vault-token."
       - "You must ensure at least 1 management server is defined in cluster_hosts, please check cluster_example_hosts for a reference."
       - "If you encounter any problems or have any concerns, please contact support@teamwire.eu"
    run_once: true
    when: groups['all'] | length() > 1

- hosts: local:management_servers
  roles:
  - role: ../../roles/management

- name: Install database backup & restore script
  hosts: local:management_servers
  tasks:
    - include_role:
        name: ../../roles/db
        tasks_from: backupscript

- name: Clean-up non-management servers
  hosts: all:!management_servers
  tasks:
    - include_role:
        name: ../../roles/management
        tasks_from: cleanup
      when: groups['all'] | length() > 1
