# Before installing Consul set up DNS with local dnsmasq
- name: Ensure dns_servers are configured before installing dnsmasq
  fail: msg="DNS servers are not defined. Please check the configuration file"
  when: dns_servers is not defined

- name: Install dnsmasq
  apt: pkg=dnsmasq

- service:
    name: dnsmasq
    state: started
    enabled: true

- name: Configure dnsmasq upstream DNS servers
  template:
    src: 20-upstream.j2
    dest: /etc/dnsmasq.d/20-upstream
  when: dns_servers is defined
  notify: restart dnsmasq

- name: Resolve DNS using dnsmasq
  copy:
    content: "nameserver 127.0.0.1\n"
    dest: /etc/resolv.conf

- name: Configure DHCP client to use local DNS server
  lineinfile:
    regexp: "^#+prepend domain-name-servers"
    backrefs: yes
    line: "prepend domain-name-servers 127.0.0.1;"
    dest: /etc/dhcp/dhclient.conf

# Ensure we have a valid DNS configuragtion
- meta: flush_handlers

# Consul
- name: Create 3rd party download directory
  file:
    dest: /var/cache/downloads
    state: directory
    mode: 0755

- name: Check if Consul is already installed
  stat: path=/usr/local/bin/consul
  register: consul_binary

- name: Download Consul
  get_url:
    url: https://releases.hashicorp.com/consul/0.7.1/consul_0.7.1_linux_amd64.zip
    dest: /var/cache/downloads/consul_0.7.1_linux_amd64.zip
    checksum: sha256:5dbfc555352bded8a39c7a8bf28b5d7cf47dec493bc0496e21603c84dfe41b4b
  register: consul_downloaded

- name: Install the Consul binary
  unarchive:
    src: /var/cache/downloads/consul_0.7.1_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    copy: no
  notify: restart consul
  when: consul_downloaded.changed or not consul_binary.stat.exists

- name: Check if Consul web UI is already installed
  stat: path=/usr/local/share/consul-ui/index.html
  register: consul_web_ui
  when: inventory_hostname in groups['consul_servers']

- name: download consul-ui
  get_url:
    url: https://releases.hashicorp.com/consul/0.7.1/consul_0.7.1_web_ui.zip
    dest: /var/cache/downloads/consul_0.7.1_web_ui.zip
    checksum: sha256:1b793c60e1af24cc470421d0411e13748f451b51d8a6ed5fcabc8d00bfb84264
  register: consul_ui_downloaded
  when: inventory_hostname in groups['consul_servers']

- name: Create the Consul web UI directory
  file:
    name: /usr/local/share/consul-ui
    state: directory
  when: inventory_hostname in groups['consul_servers']

- name: Install the Consul web UI
  unarchive:
    src: /var/cache/downloads/consul_0.7.1_web_ui.zip
    dest: /usr/local/share/consul-ui
    copy: no
  when: inventory_hostname in groups['consul_servers'] and (consul_ui_downloaded.changed or not consul_web_ui.stat.exists)

- name: Create Consul config directory
  file:
    name: /etc/consul.d
    state: directory

- name: Write Consul server configuration file
  template:
    src: 10-server.json.j2
    dest: /etc/consul.d/10-server.json
  when: '"consul_servers" in group_names'
  notify: restart consul

- name: Write Consul agent configuration file
  template:
    src: 20-agent.json.j2
    dest: /etc/consul.d/20-agent.json
  notify: restart consul

- name: Install Consul upstart job
  copy:
    src: consul.conf
    dest: /etc/init/consul.conf
  notify: restart consul
  when: ansible_distribution == "Ubuntu"

- name: Install Consul systemd config
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service
  notify:
    - reload systemd
    - restart consul
  when: ansible_distribution == "Debian"

# redirect DNS to consul
- name: Add consul forwarding to dnsmasq
  template:
    src: 10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
  notify: restart dnsmasq

- service:
    name: consul
    state: started
    enabled: yes
- meta: flush_handlers
