- name: Create 3rd party download directory
  file:
    dest: /var/cache/downloads
    state: directory
    mode: 0755

- name: Check if Consul is already installed
  stat: path=/usr/local/bin/consul
  register: consul_binary

- name: Download Consul
  get_url:
    url: https://releases.hashicorp.com/consul/{{consul_version}}/consul_{{consul_version}}_linux_amd64.zip
    dest: /var/cache/downloads/consul_{{consul_version}}_linux_amd64.zip
    checksum: "sha256:{{consul_checksum}}"
  register: consul_downloaded

- name: Install the Consul binary
  unarchive:
    src: /var/cache/downloads/consul_{{consul_version}}_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    copy: no
  notify: restart consul
  when: consul_downloaded.changed or not consul_binary.stat.exists

- name: Create Consul config directory
  file:
    name: /etc/consul.d
    state: directory

- name: Write Consul server configuration file
  template:
    src: 10-server.json.j2
    dest: /etc/consul.d/10-server.json
  when: '"consul_servers" in group_names'
  notify: restart consul

- name: Write Consul agent configuration file
  template:
    src: 20-agent.json.j2
    dest: /etc/consul.d/20-agent.json
  notify: restart consul

- name: Install Consul systemd config
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service
  notify:
    - reload systemd
    - restart consul

# redirect DNS to consul
- name: Add consul forwarding to dnsmasq
  template:
    src: 10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
  notify: restart dnsmasq

 # Remove old consul-ui, hash-ui is used instead
- name: Check if consul-ui is installed
  stat: path=/usr/local/share/consul-ui
  register: consului

- name: Remove old consul-ui
  when: consului.stat.exists
  file:
    path: /usr/local/share/consul-ui
    state: absent

- service:
    name: consul
    state: started
    enabled: yes
- meta: flush_handlers
