# Before installing Consul set up DNS with local dnsmasq
- name: Ensure dns_servers are configured before installing dnsmasq
  fail: msg="DNS servers are not defined. Please check the configuration file"
  when: config_done is defined and dns_servers is not defined

- name: Install dnsmasq
  apt: pkg=dnsmasq
- service: name=dnsmasq state=started enabled=true

- name: Configure dnsmasq upstream DNS servers
  template: src=20-upstream.j2 dest=/etc/dnsmasq.d/20-upstream
  when: dns_servers is defined
  notify: restart dnsmasq

- name: Resolve DNS using dnsmasq
  copy: content="nameserver 127.0.0.1\n" dest=/etc/resolv.conf

- name: Configure DHCP client to use local DNS server
  lineinfile:
    regexp="^#+prepend domain-name-servers"
    backrefs=yes
    line="prepend domain-name-servers 127.0.0.1;"
    dest=/etc/dhcp/dhclient.conf

# Ensure we have a valid DNS configuragtion
- meta: flush_handlers

# Consul
- name: Download Consul
  get_url:
    url: https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
    dest: /root/consul_0.6.4_linux_amd64.zip
    checksum: sha256:abdf0e1856292468e2c9971420d73b805e93888e006c76324ae39416edcf0627
  register: consul_downloaded

- name: Install the Consul binary
  unarchive: src=/root/consul_0.6.4_linux_amd64.zip dest=/usr/local/bin mode=0755 copy=no
  notify: restart consul
  when: consul_downloaded.changed

- name: download consul-ui
  get_url:
    url: https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_web_ui.zip
    dest: /root/consul_0.6.4_web_ui.zip
    checksum: sha256:5f8841b51e0e3e2eb1f1dc66a47310ae42b0448e77df14c83bb49e0e0d5fa4b7
  register: consul_ui_downloaded

- name: Create the Consul web UI directory
  file: name=/usr/local/share/consul-ui state=directory

- name: Install the Consul web UI
  unarchive: src=/root/consul_0.6.4_web_ui.zip dest=/usr/local/share/consul-ui copy=no
  when: consul_ui_downloaded.changed

- name: Create Consul config directory
  file: name=/etc/consul.d state=directory

- name: Write Consul server configuration file
  template: src=10-server.json.j2 dest=/etc/consul.d/10-server.json
  when: '"consul_servers" in group_names'
  notify: restart consul

- name: Write Consul agent configuration file
  template: src=20-agent.json.j2 dest=/etc/consul.d/20-agent.json
  notify: restart consul

- name: Install Consul upstart job
  copy: src=consul.conf dest=/etc/init/consul.conf
  notify: restart consul
  when: ansible_distribution == "Ubuntu"

- name: Install Consul systemd config
  copy: src=consul.service dest=/etc/systemd/system/consul.service
  notify:
    - reload systemd
    - restart consul
  when: ansible_distribution == "Debian"

- name: Install Consul default
  template: src=default.j2 dest=/etc/default/consul
  notify: restart consul

# redirect DNS to consul
- name: Add consul forwarding to dnsmasq
  template: src=10-consul.j2 dest=/etc/dnsmasq.d/10-consul
  notify: restart dnsmasq

- service: name=consul state=started enabled=yes
- meta: flush_handlers
