---
# install ntp and set timezone to UTC
- name: set timezone to UTC
  copy: content='Etc/UTC' dest=/etc/timezone
  notify: update timezone
- template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart NTP
- apt: pkg=ntp
- service: name=ntp state=started enabled=true

- name: Install useful tools
  apt: name={{item}} state=present
  with_items:
  - htop
  - sysstat
  - iotop

- name: Remove useless packages
  apt: pkg={{item}} state=absent
  with_items:
  - mlocate # sucks IO heavily

- name: disable SSH password root logins
  action: lineinfile dest=/etc/ssh/sshd_config regexp=^#?PasswordAuthentication line="PasswordAuthentication no"
  notify: reload sshd
