---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart NTP
  service: name=ntp state=restarted

- name: reload sshd
  service: name=ssh state=reloaded

- name: rebuild postfix passwd map
  command: postmap /etc/postfix/sasl/passwd

- name: rebuild postfix generic map
  command: postmap /etc/postfix/generic

- name: restart postfix
  service: name=postfix state=restarted

- name: fix ownership of git checkout
  file: path=/home/teamwire/platform owner=teamwire group=teamwire recurse=yes

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: new aliases
  command: newaliases

- name: rebuild postfix domain map
  command: postmap /etc/postfix/virtual
