---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart NTP
  service: name=ntp state=restarted

- name: reload sshd
  service: name=ssh state=reloaded

- name: rebuild postfix passwd map
  command: postmap /etc/postfix/sasl/passwd

- name: rebuild postfix generic map
  command: postmap /etc/postfix/generic

- name: restart postfix
  service: name=postfix state=restarted

- name: fix ownership of git checkout
  command: chown -R teamwire:teamwire /home/teamwire/platform
