---
- name: Check if installing a storage cluster
  set_fact:
    glusterfs_cluster: True
  when: '"nfs_servers" in groups and groups["nfs_servers"] | length > 1'

- include_tasks: single.yml
  when: glusterfs_cluster is not defined

- include_tasks: glusterfs.yml
  when: glusterfs_cluster is defined
