- name: reload systemd
  command: systemctl daemon-reload

- name: restart consul
  service: name=consul state=restarted

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: run resolvconf
  shell: resolvconf -u
