- name: Copy migrations script
  copy:
    src: "migrateGPG.sh"
    dest: "/usr/local/bin/migrateGPG.sh"
    mode: 0744
    owner: root
    group: root

- name: Check that flag file exists
  stat:
    path: "/etc/gpg2Migration"
  register: flagfile

- name: Create migration flag file
  copy:
    dest: "/etc/gpg2Migration"
    content: "{{ lookup('env','GPG_ISENABLED')| default('0') }}"
    mode: 0644
  when: not flagfile.stat.exists