- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
   
  - include_vars: ../../roles/common/vars/main.yml
  - include_vars: ../../group_vars/all

  - name: Check pip Ansible version
    shell: pip show ansible | awk '$1 ~ /Version/ {print $2}'
    register: pip_ansible_version

  - debug:
      msg:
        - "About to remove the old Ansible package"
        - "After this procedure has executed, you will need to refresh your session sources"
        - "You can do this by either executing source ~/.bashrc or exiting and rejoining the SSH session"
        - "After performing this, you can run the usual playbook process"
        - "If you encounter any issues, please email support@teamwire.eu"
    when: pip_ansible_version.stdout == required_ansible_version

  - name: Retain Ansible dependencies
    shell: apt-mark manual libyaml-0-2 python-crypto python-ecdsa python-httplib2 python-jinja2 python-markupsafe python-paramiko python-yaml
    ignore_errors: yes   
    when: pip_ansible_version.stdout == required_ansible_version

  - name: Remove old Ansible package
    apt: 
      name: ansible
      state: absent
    when: pip_ansible_version.stdout == required_ansible_version
