---
- hosts: all
  tasks:
  - name: Get slave status
    mysql_replication:
      mode: getslave
      login_user: root
      login_password: "{{mysql_root_password}}"
    register: mysql_slave_state

  - name: Get master binlog file name and binlog position
    mysql_replication:
      mode: getmaster
      login_host: "{{partner_node}}"
      login_user: repl
      login_password: "{{replication_password}}"
    register: mysql_master_state

  - name: MySQL slave status
    debug:
      var: mysql_slave_state
  - name: MySQL master status
    debug:
      var: mysql_master_state

  - name: Configure replication
    mysql_replication:
      mode: changemaster
      master_host: "{{partner_node}}"
      master_user: repl
      master_password: "{{replication_password}}"
      master_log_file: "{{mysql_master_state.File}}"
      master_log_pos: "{{mysql_master_state.Position}}"
      login_user: root
      login_password: "{{mysql_root_password}}"
    register: mysql_replication
    when: not mysql_slave_state.Is_Slave

  - name: Activate replication
    mysql_replication:
      mode: startslave
      login_user: root
      login_password: "{{mysql_root_password}}"
    when: 'mysql_replication.changed or (mysql_slave_state.Slave_IO_Running == "No" or mysql_slave_state.Slave_SQL_Running == "No")'
