- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:

  - include_vars: ../../roles/common/vars/main.yml
  - include_vars: ../../group_vars/all

  - name: Checking if Ansible {{ required_ansible_version }} is already installed
    fail: msg="This server is already running Ansible {{ required_ansible_version }}. Upgrade not required."
    when: ansible_version['full'] == required_ansible_version

  - name: Install Pip requirements
    apt: name={{item}} state=present
    with_items:
    - python-pip
    - python-wheel
    - python-setuptools

  - name: Enforce pip version {{ required_pip_version }}
    pip:
      name=pip
      version={{ required_pip_version }}
      extra_args={{ "--proxy="+http_proxy if http_proxy is defined else omit }}

  - debug:
      msg:
        - "About to install Ansible version {{ required_ansible_version }}"
        - "After this procedure has executed, you will need to refresh your session sources"
        - "You can do this by either executing source ~/.bashrc or exiting and rejoining the SSH session"
        - "After performing this, you you will need to run the post-ansible-upgrade procedure."
        - "If running a single-server setup, run: ansible-playbook -i hosts playbooks/procedures/post-ansible-upgrade.yml"
        - "If running a clustered-server setup, run: ansible-playbook -i cluster_hosts playbooks/procedures/post-ansible-upgrade.yml"
        - "If you encounter any issues, please email support@teamwire.eu"

  - name: Install Ansible version {{ required_ansible_version }}
    pip:
      name=ansible
      version={{ required_ansible_version }}
      extra_args={{ "--proxy="+http_proxy if http_proxy is defined else omit }}
    when: ansible_version['full'] != required_ansible_version
    become: true
