- hosts: all
  tasks:
   
  - include_vars: ../../roles/common/vars/main.yml
  - include_vars: ../../group_vars/all

  - name: Checking if Ansible {{ required_ansible_version }} is already installed
    fail: msg="This server is already running Ansible {{ required_ansible_version }}. Upgrade not required."
    when: ansible_version['full'] == required_ansible_version

  - name: apt-get update
    apt: update_cache=yes

  - name: Install Ansible requirements
    apt: name={{item}} state=present
    with_items:
    - python-setuptools
    - python-pip
    - python-wheel

  - name: Install latest stable Ansible
    pip:
      name=ansible
      version={{ required_ansible_version }}
      extra_args={{ "--proxy="+http_proxy if http_proxy is defined else omit }}
    when: ansible_version['full'] != required_ansible_version

  - name: Check pip Ansible version
    shell: pip show ansible | awk '$1 ~ /Version/ {print $2}'
    register: pip_ansible_version

  - debug:
      msg:
        - "About to remove the old Ansible package"
        - "After this procedure has executed, you will need to refresh your session sources"
        - "You can do this by either executing source ~/.bashrc or exiting and rejoining the SSH session"
        - "After performing this, you can run the usual playbook process"
        - "If you encounter any issues, please email support@teamwire.eu"
    when: pip_ansible_version.stdout == required_ansible_version
    
  - name: Remove old Ansible package
    apt: 
      name: ansible
      state: absent
    when: pip_ansible_version.stdout == required_ansible_version
