---
- name: reload systemd
  command: systemctl daemon-reload

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: restart haproxy
  service: name=haproxy state=restarted

- name: restart Consul Template
  service: name=consul-template state=restarted
