---
- name: reload systemd
  command: systemctl daemon-reload

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart Consul Template
  service: name=consul-template state=restarted
