---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart docker
  service: name=docker state=restarted

- name: restart logspout
  service: name=logspout state=restarted enabled=true
