---
- hosts: all
  pre_tasks:
    - name: Check Ansible version
      assert:
        that: "ansible_version.full is version_compare('2.5.4', '>=')"
        msg:
          - "Ansible 2.5.4 is required, please run the upgrade procedure"
          - "If running a single-server setup, run: ansible-playbook -i hosts playbooks/procedures/upgrade-ansible.yml"
          - "If running a clustered-server setup, run: ansible-playbook -i cluster_hosts playbooks/procedures/upgrade-ansible.yml"

- name: Vault Status check
  hosts: local:consul_servers
  tasks:
    - include_role:
        name: roles/vault.yml
        tasks_from: secrets
      when: ansible_local.vault is defined and ansible_local.vault.initialized == "true" and secrets_read is not defined

- include: roles/common.yml
- include: roles/consul.yml
- include: roles/vault.yml
- include: roles/nfs_servers.yml
- include: roles/storage_client.yml
- include: roles/database_servers.yml
- include: roles/backend.yml
- include: roles/nomad.yml
- include: roles/container.yml
- include: roles/loghost.yml
- include: roles/docker.yml
- include: roles/redis_servers.yml
- include: roles/frontend.yml
- include: roles/load_balancers.yml
- include: roles/monitoring.yml
