---
- name: restart systemd Haproxy
  systemd: daemon_reload=yes name=haproxy state=restarted enabled=yes

- name: reload HAProxy
  systemd: name=haproxy state=reloaded

- name: restart haproxy
  systemd: name=haproxy state=restarted
