---
- include: configuration.yml

- name: Create compose config directory
  file: dest=/usr/share/teamwire state=directory mode=0770

# Arcane path sorcery; required as this file is only included from the playbook
- name: Install the container helper tool
  copy: src=../../roles/backend/files/twctl dest=/usr/local/bin/twctl mode=0755 owner=root group=root

- name: Write compose file
  template:
    src: ../../roles/backend/templates/docker-compose.yml.j2
    dest: /usr/share/teamwire/docker-compose.yml
    mode: 0660

- name: write cluster configuration file
  template:
    src: ../../roles/backend/templates/cluster.conf.j2
    dest: /usr/share/teamwire/cluster.conf
    mode: 0640

- docker_service:
    project_name: teamwire
    project_src: /usr/share/teamwire
    docker_host: "tcp://{{ private_ip | ipaddr('address') }}:4000"
# FIXME: the docker_service module doesn't accept variables as parameters for the
# scale setting; this needs to be calculated dynamically once ansible is fixed.
# see https://github.com/ansible/ansible-modules-core/issues/4592
    scale:
      backend: 3
      worker: 3
      screenshot-server: 3
