---
- include: configuration.yml

- name: Create compose config directory
  file: dest=/data/cluster_config state=directory mode=0770 owner=root group=teamwire
  run_once: true

- name: Write compose file
  run_once: true
  template:
    src: ../../roles/backend/templates/docker-compose.yml.j2
    dest: /data/cluster_config/docker-compose.yml
    mode: 0660
    owner: root
    group: teamwire

- name: write cluster configuration file
  run_once: true
  template:
    src: ../../roles/backend/templates/cluster.conf.j2
    dest: /data/cluster_config/cluster.conf
    mode: 0640
    owner: root
    group: teamwire

# Arcane path sorcery; required as this file is only included from the playbook
- name: Install the container helper tool
  copy: src=../../roles/backend/files/twctl dest=/usr/local/bin/twctl mode=0755 owner=root group=root

- name: Install the database charset correction tool
  copy: src=../../roles/backend/files/dbconvert dest=/usr/local/bin/dbconvert mode=0755 owner=root group=root
