---
- name: Install HAProxy
  apt:
    pkg: "{{ item }}"
  with_items:
    - haproxy
    - hatop

- name: Install HAproxy systemd config
  copy:
    src: "{{ haproxy_service_file }}"
    dest: /etc/systemd/system/haproxy.service
  notify: restart systemd Haproxy

- name: Replace HAproxy wrapper in debian 10
  replace:
     path: "/etc/systemd/system/haproxy.service"
     regexp: "/usr/sbin/haproxy-systemd-wrapper"
     replace: "/usr/sbin/haproxy -Ws"
  when: ansible_distribution_release == "buster"
  notify: restart systemd Haproxy

- name: Remove default HAproxy configs
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/haproxy/haproxy.cfg
    - /etc/haproxy/haproxy.cfg.bak
  notify: reload HAProxy

- name: Write HAProxy globals and galera configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0664
    owner: haproxy
    group: haproxy
  with_items:
    - { src: '{{ globals_haproxy_template }}', dest: '/etc/haproxy/01-globals.cfg' }
    - { src: '{{ galera_haproxy_template }}', dest: '/etc/haproxy/02-galera.cfg' }
  notify: restart haproxy

- name: Generate a new Diffie-Hellman group
  command: /usr/bin/openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
  when: ssl_keyfile is defined
  args:
    creates: /etc/ssl/private/dhparams.pem
