---
# Create the backend storage directories
- file: path=/data owner=daemon mode=0750 state=directory
- file: path=/data/assets owner=daemon mode=0750 state=directory
- file: path=/data/website-screenshot-cache owner=daemon mode=0750 state=directory
- file: path=/data/certs owner=root group=daemon mode=0750 state=directory
- file: path=/data/certs/apns owner=root group=daemon mode=0750 state=directory
- file: path=/data/beat owner=daemon mode=0750 state=directory

- name: Install the APNS certificate
  when: config_done is defined
  copy: src="{{ apns_certificate }}" dest=/data/certs/apns/aps-production.pem mode=0640 group=daemon

# Install docker and the backend container and run it
- apt_key: id=A88D21E9 keyserver=hkp://keyserver.ubuntu.com:80 state=present
- apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
- apt: pkg=lxc-docker state=present
- apt: pkg=python-pip state=present
- pip: name=docker-py version=1.0.0
- user: name=teamwire groups=docker append=yes

- name: Retrieve and run the Teamwire backend main container
  when: config_done is defined
  docker:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
    email: "{{ dockerhub_email }}"

    name: teamwire_backend
    image: "teamwire/backend:prod"
    state: running
    net: bridge
    ports: "8080:8080"
    volumes: "/data/assets:/assets"
    env:
      AESKEY: "{{aes_key}}"
      MYSQL_HOST: "{{mysql_host}}"
      MYSQL_PORT: "{{mysql_port}}"
      MYSQL_PASSWORD: "{{teamwire_db_password}}"
      REDIS_URI: "172.17.42.1:6379:1"
      EMAIL_HOST: 172.17.42.1
      BLOB_DIR: /assets
      DEFAULT_FROM_EMAIL: "{{sender_address}}"
      FAKE_PIN: "{{ fake_pin|default() }}"
      FAKE_SMS: "{{ fake_sms|default() }}"
      FAKE_EMAIL_CONFIRMATION: "{{ fake_email_confirmation|default() }}"
      FAKE_DB_ENCRYPTION: "{{ fake_db_encryption|default() }}"

- name: Run the Teamwire backend worker container
  when: config_done is defined
  docker:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
    email: "{{ dockerhub_email }}"

    name: teamwire_worker
    image: "teamwire/backend:prod"
    state: running
    net: bridge
    volumes: "/data/assets:/assets,/data/certs/apns/:/app/certs/apns/"
    env:
      MODE: worker
      AESKEY: "{{aes_key}}"
      MYSQL_HOST: "{{mysql_host}}"
      MYSQL_PORT: "{{mysql_port}}"
      MYSQL_PASSWORD: "{{teamwire_db_password}}"
      REDIS_URI: "172.17.42.1:6379:1"
      BLOBDIR: /assets
      APNS_CERT_1: "/app/certs/apns/aps-production.pem,push_production,{{ apns_appid|default('com.teamwire.messenger') }}"
      GCM_API_KEY: "{{ gcm_api_key }}"
      FAKE_DB_ENCRYPTION: "{{ fake_db_encryption|default() }}"

- name: Run the Teamwire beat container
  when: config_done is defined
  docker:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
    email: "{{ dockerhub_email }}"

    name: teamwire_beat
    image: "teamwire/backend:prod"
    state: running
    net: bridge
    volumes: "/data/beat:/beat"
    env:
      MODE: beat
      AESKEY: "{{aes_key}}"
      MYSQL_HOST: "{{mysql_host}}"
      MYSQL_PORT: "{{mysql_port}}"
      MYSQL_PASSWORD: "{{teamwire_db_password}}"
      REDIS_URI: "172.17.42.1:6379:1"
      CELERY_BEAT_SCHEDULE: /beat/celerybeat-schedule
      FAKE_DB_ENCRYPTION: "{{ fake_db_encryption|default() }}"

- name: Run the Teamwire backend web screenshot container
  when: config_done is defined
  docker:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
    email: "{{ dockerhub_email }}"

    name: teamwire_screenshot_server
    image: "teamwire/web-screenshot-server:prod"
    state: running
    net: bridge
    ports: "8081:8080"
    volumes: "/data/website-screenshot-cache:/website-screenshot-cache"
    env:
      CACHE_DIR: /website-screenshot-cache

- name: Install the backend container upstart configuration
  when: config_done is defined
  template: src=docker-upstart.conf.j2 dest="/etc/init/teamwire_{{ item }}.conf"
  with_items:
   - backend
   - worker
   - beat
   - screenshot_server

  # Install and configure the nginx frontend proxy server
  # Copy the SSL certificate
- copy: src={{ ssl_certfile }} dest=/etc/ssl/teamwire-backend.crt
  when: ssl_certfile is defined

- copy: src={{ ssl_keyfile }} dest=/etc/ssl/teamwire-backend.key
  when: ssl_keyfile is defined

- name: Install nginx
  apt: name=nginx-light state=present

- template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx
- template: src=teamwire-backend-http.j2 dest=/etc/nginx/sites-available/teamwire-backend-http
- template: src=teamwire-backend-https.j2 dest=/etc/nginx/sites-available/teamwire-backend-https

- name: Disable nginx default site
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Enable HTTP
  when: ssl_certfile is not defined and ssl_keyfile is not defined
  file:
    src: /etc/nginx/sites-available/teamwire-backend-http
    dest: /etc/nginx/sites-enabled/teamwire-backend-http
    state: link
  notify: reload nginx

- name: Disable HTTP
  when: ssl_certfile is defined and ssl_keyfile is defined
  file:
    path: /etc/nginx/sites-enabled/teamwire-backend-http
    state: absent
  notify: reload nginx

- name: Enable HTTPS
  when: ssl_certfile is defined and ssl_keyfile is defined
  file:
    src: /etc/nginx/sites-available/teamwire-backend-https
    dest: /etc/nginx/sites-enabled/teamwire-backend-https
    state: link
  notify: reload nginx

# open firewall ports for the web server
- ufw: rule=allow port=80 proto=tcp
  when: config_done is defined and ssl_certfile is not defined and ssl_keyfile is not defined
- ufw: rule=allow port=80 proto=tcp delete=yes
  when: ssl_certfile is defined and ssl_keyfile is defined
- ufw: rule=allow port=443 proto=tcp
  when: ssl_certfile is defined and ssl_keyfile is defined
