---
- include: ../../backend/tasks/configuration.yml

- name: Wait for nomad API port to start listening
  wait_for:
    port: 4646
  run_once: true

- name: Obtain total CPU compute power
  shell: nomad node-status -self -json | awk -F'[^0-9]*' '/cpu.totalcompute/{print $2}'
  register: cpu_calculation
  run_once: true
  changed_when: False

- name: Set facts for total CPU power (cores*frequency) on Nomad clients
  set_fact:
    core_count: "{{ ansible_processor_vcpus }}"
    total_cpu_power: "{{ cpu_calculation.stdout }}"

- name: Write Teamwire cluster nomad job
  template:
    src: teamwire.nomad.j2
    dest: /data/cluster_config/teamwire.nomad
    owner: teamwire
  run_once: true

