---
- name: Run registrator in clustered setups
  when: private_ip is defined and 'consul_servers' in groups
  docker:
    name: registrator
    image: "gliderlabs/registrator:latest"
    state: reloaded
    restart_policy: always
    net: host
    volumes: "/var/run/docker.sock:/tmp/docker.sock"
    command: "-ip {{ private_ip | ipaddr('address') }} consul://localhost:8500"

- name: Run Swarm manager
  when: "'consul_servers' in group_names"
  docker:
    name: swarm-manager
    image: "swarm:1.2.5"
    state: reloaded
    restart_policy: always
    net: host
    ports: "4000:4000"
    command: "manage -H :4000 --replication --advertise {{ private_ip | ipaddr('address') }}:4000 consul://localhost:8500"

- name: Ensure pip is installed on manager nodes
  apt: pkg=python-pip state=present install_recommends=no
  when: "'consul_servers' in group_names"

- name: Ensure docker-compose is installed on manager nodes
  pip: name=docker-compose version=1.8.0
  when: "'consul_servers' in group_names"

- name: Run Swarm agent
  when: "'backend_servers' in group_names"
  docker:
    name: swarm-agent
    image: "swarm:1.2.5"
    state: reloaded
    restart_policy: always
    net: host
    command: "join --advertise={{ private_ip | ipaddr('address') }}:2375 consul://localhost:8500"

