---
- name: Run registrator in clustered setups
  when: private_ip is defined and 'consul_servers' in groups
  docker:
    name: registrator
    image: "{{ registrator_version }}"
    state: reloaded
    restart_policy: always
    log_driver: syslog
    log_opt:
      tag: registrator
      syslog-facility: local6
    net: host
    volumes: "/var/run/docker.sock:/tmp/docker.sock"
    command: "-ip {{ private_ip }} consul://localhost:8500"
