---
- name: Write logspout configutation
  when: private_ip is defined and 'loghost' in groups
  template: src=logspout.j2 dest=/etc/default/logspout
  notify:
    - restart logspout

- name: Install logspout in clustered setups
  when: private_ip is defined and 'loghost' in groups
  template: src=logspout.service.j2 dest=/etc/systemd/system/logspout.service
  notify:
    - reload systemd
    - restart logspout

- name: Run registrator in clustered setups
  when: private_ip is defined and 'consul_servers' in groups
  docker:
    name: registrator
    image: "{{ registrator_version }}"
    state: reloaded
    restart_policy: always
    net: host
    volumes: "/var/run/docker.sock:/tmp/docker.sock"
    command: "-ip {{ private_ip | ipaddr('address') }} consul://localhost:8500"

- name: Run Swarm manager
  when: "'consul_servers' in group_names"
  docker:
    name: swarm-manager
    image: "{{ swarm_version }}"
    state: reloaded
    restart_policy: always
    net: host
    ports: "4000:4000"
    command: "manage -H :4000 --replication --advertise {{ private_ip | ipaddr('address') }}:4000 consul://localhost:8500"

- name: Ensure pip and Docker Compose requirements are installed on manager nodes
  apt: pkg={{ item }} state=present default_release=jessie-backports install_recommends=no
  when: "'consul_servers' in group_names"
  with_items:
    - python-pip
    - python-backports.ssl-match-hostname
    - python-docopt
    - python-enum34
    - python-functools32
    - python-ipaddress
    - python-jsonschema
    - python-requests
    - python-texttable

- name: Check if a wheelhouse exists
  stat: path=/var/cache/wheelhouse
  register: wheelhouse

- name: Ensure docker-py 1.9.0 is installed on manager nodes (online)
  pip: name=docker-py version=1.9.0
  when: "'consul_servers' in group_names and not wheelhouse.stat.exists"

- name: Ensure docker-compose is installed on manager nodes (online)
  pip: name=docker-compose version=1.8.0
  when: "'consul_servers' in group_names and not wheelhouse.stat.exists"

- name: Ensure docker-compose is installed on manager nodes (offline)
  pip: name=/var/cache/wheelhouse/{{ item }} extra_args="--no-deps"
  when: "'consul_servers' in group_names and wheelhouse.stat.exists"
  with_items:
    - cached_property-1.2.0-py2.py3-none-any.whl
    - dockerpty-0.4.1-py2-none-any.whl
    - websocket_client-0.32.0-py2-none-any.whl
    - docker_py-1.9.0-py2.py3-none-any.whl
    - docker_compose-1.8.0-py2-none-any.whl

# docker-compose pulls in reqeusts 2.7, which breaks pip, so we need to remove
# the local installation; compose seems to work fine with requests 2.8 from
# backports
- name: Remove outdated version of python requests module
  file: path={{item}} state=absent
  when: "'consul_servers' in group_names and not wheelhouse.stat.exists"
  with_items:
    - /usr/local/lib/python2.7/dist-packages/requests
    - /usr/local/lib/python2.7/dist-packages/requests-2.7.0.dist-info

- name: Run Swarm agent
  when: "'backend_servers' in group_names"
  docker:
    name: swarm-agent
    image: "{{ swarm_version }}"
    state: reloaded
    restart_policy: always
    net: host
    command: "join --advertise={{ private_ip | ipaddr('address') }}:2375 consul://localhost:8500"
