---
# Install docker and the backend container and run it
- apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=hkp://p80.pool.sks-keyservers.net:80 state=present
  when: http_proxy is not defined
- command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --keyserver-options http-proxy="{{http_proxy}}" --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  when: http_proxy is defined
- apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
- apt: pkg=docker-engine state=present
- apt: pkg=python-pip state=present
- pip: name=docker-py version=1.0.0
- user: name=teamwire groups=docker append=yes

- name: Configure proxy for docker
  when: http_proxy is defined
  lineinfile: dest=/etc/default/docker regexp=http_proxy line='export http_proxy="{{http_proxy}}"'
  notify: restart docker

- name: Log in on Docker Hub
  command: docker login -e "{{ dockerhub_email }}" -u "{{ dockerhub_username }}" -p "{{ dockerhub_password }}"
  become: True
  become_user: teamwire
  when: config_done is defined
  args:
    creates: /home/teamwire/.docker/config.json

# Make sure docker is restarted before the containers are set up, otherwise
# the restart would kill the running containers.
- meta: flush_handlers
