---
- name: Create Docker Registry storage directory
  file: name=/data/registry state=directory mode=0750
  run_once: true

- name: Write Docker registry config file
  template: src=registry-config.yml.j2 dest=/data/registry/config.yml
  run_once: true

- name: Retrieve the  Docker Registry container
  when: config_done is defined
  docker_image:
    name: "{{ registry_version }}"
    state: present

- name: Run the Docker Registry container
  when: config_done is defined
  docker_container:
    name: docker-registry
    image: "{{ registry_version }}"
    state: started
    restart_policy: always
    network_mode: bridge
    ports: "5000:5000"
    volumes: "/data/registry:/var/lib/registry,/data/registry/config.yml:/etc/docker/registry/config.yml"

# Push all local images to the local registry
- name: Copy the registry image helper tool
  copy: src=twimg dest=/usr/local/bin/ mode=0755

- name: Push local images to registry
  command: /usr/local/bin/twimg --registry "{{ inventory_hostname }}:5000" push
  when: offline_mode.stat.exists
  run_once: true
