---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: Configure Consul on all nodes
  hosts: all
  serial: 1
  roles:
    - consul

- name: Deploy and configure MySQL database
  hosts: database_servers
  roles:
    - { role: db, when: config_done is defined and mysql_host is not defined }

- name: Deploy and configure Redis database cluster
  hosts: redis_servers
  serial: 1
  roles:
    - docker
    - redis

- name: Deploy and configure Docker registry
  hosts: docker_registry
  roles:
    - docker
    - { role: docker-registry, when: config_done is defined }

- name: Deploy and configure NFS server
  hosts: nfs_server
  roles:
    - { role: storage, when: config_done is defined and external_storage_path is not defined }

- name: Deploy and configure the backend servers
  hosts: backend_servers
  roles:
    - docker
    - web

- name: Deploy and configure the load balancers
  hosts: load_balancers
  roles:
    - load_balancer
