---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: Deploy and configure MySQL database
  hosts: database_server
  roles:
    - { role: db, when: config_done is defined and mysql_host is not defined }

- name: Deploy and configure Redis database
  hosts: database_server
  roles:
    - redis

- name: Deploy and configure Docker registry
  hosts: docker_registry
  roles:
    - docker
    - { role: docker-registry, when: config_done is defined }

- name: Deploy and configure NFS server
  hosts: nfs_server
  roles:
    - { role: storage, when: config_done is defined and external_storage_path is not defined }

- name: Deploy and configure the backend servers
  hosts: backend_servers
  roles:
    - docker
    - web
  vars:
    - redis_host: "{{ hostvars[groups['database_server'][0]].ansible_eth0.ipv4.address }}"
    - mysql_host: "{{ hostvars[groups['database_server'][0]].ansible_eth0.ipv4.address }}"
