---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: Deploy and configure MySQL database
  hosts: all
  roles:
    - { role: db, when: config_done is defined and mysql_host is not defined }

- name: Deploy and configure Redis database
  hosts: all
  roles:
    - { role: redis, when: config_done is defined and redis_host is not defined }

- name: Deploy and configure the backend server
  hosts: all
  roles:
    - docker
    - web
