---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: Deploy and configure MySQL database
  hosts: all
  roles:
    - { role: db, when: config_done is defined and mysql_host == "172.17.0.1" }

- name: Deploy and configure Redis database
  hosts: all
  roles:
    - { role: redis, when: config_done is defined }

- name: Deploy and configure the backend server
  hosts: all
  roles:
    - web
